name: litefarm_new
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.7.0
  - appdirs=1.4.4
  - appnope=0.1.4
  - asttokens=2.4.1
  - backports=1.0
  - backports.tarfile=1.2.0
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cachecontrol=0.14.3
  - cachecontrol-with-filecache=0.14.3
  - click-default-group=1.2.4
  - colorama=0.4.6
  - comm=0.2.2
  - conda-lock=3.0.2
  - crashtest=0.4.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - distlib=0.3.9
  - dulwich=0.22.8
  - ensureconda=1.4.7
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.18.0
  - gitdb=4.0.12
  - gitpython=3.1.44
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.3
  - ipython_pygments_lexers=1.1.1
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.1.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyring=25.6.0
  - krb5=1.21.2
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - matplotlib-inline=0.1.7
  - more-itertools=10.7.0
  - msgpack-python=1.1.0
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - pkginfo=1.12.1.2
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pydantic=2.11.4
  - pydantic-core=2.33.2
  - pygments=2.18.0
  - pyproject_hooks=1.2.0
  - pysocks=1.7.1
  - python=3.12.3
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-installer=0.7.0
  - python_abi=3.12
  - pyzmq=26.0.3
  - readline=8.2
  - requests-toolbelt=1.0.0
  - ruamel.yaml=0.18.13
  - ruamel.yaml.clib=0.2.8
  - semver=3.0.4
  - shellingham=1.5.4
  - six=1.16.0
  - smmap=5.0.2
  - stack_data=0.6.2
  - tk=8.6.13
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.4.2
  - traitlets=5.14.3
  - trove-classifiers=2025.5.9.12
  - typing-inspection=0.4.1
  - virtualenv=20.31.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xattr=1.1.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstandard=0.23.0
  - pip:
      - ace==0.3.3
      - altair==5.4.1
      - altair-data-server==0.4.1
      - altair-saver==0.5.0
      - altair-viewer==0.4.0
      - anyio==4.6.2.post1
      - anywidget==0.9.11
      - asgiref==3.8.1
      - attrs==23.2.0
      - bcrypt==4.1.3
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - branca==0.7.2
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - circlify==0.15.0
      - click==8.1.7
      - contourpy==1.2.1
      - coverage==7.6.0
      - cryptography==42.0.7
      - cycler==0.12.1
      - defusedxml==0.7.1
      - et-xmlfile==1.1.0
      - faicons==0.2.2
      - fastjsonschema==2.20.0
      - folium==0.16.0
      - fonttools==4.53.1
      - fuzzywuzzy==0.18.0
      - geographiclib==2.0
      - geopandas==1.0.1
      - geopy==2.4.1
      - h11==0.14.0
      - htmltools==0.6.0
      - iniconfig==2.0.0
      - ipython==8.18.0
      - ipywidgets==8.1.2
      - itables==2.0.1
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - linkify-it-py==2.0.3
      - lxml==5.2.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mistune==3.1.3
      - narwhals==1.14.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - numpy==1.26.4
      - openpyxl==3.1.3
      - openrouteservice==2.3.3
      - orjson==3.10.11
      - outcome==1.3.0.post0
      - packaging==24.2
      - panadas==0.2
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - paramiko==3.4.0
      - patsy==0.5.6
      - pep517==0.13.1
      - pillow==10.4.0
      - platformdirs==4.2.1
      - plotly==5.22.0
      - pluggy==1.5.0
      - portpicker==1.6.0
      - pprintpp==0.4.0
      - prompt-toolkit==3.0.36
      - psycopg==3.1.18
      - psycopg-binary==3.1.18
      - psycopg2-binary==2.9.9
      - psygnal==0.11.1
      - pycountry==24.6.1
      - pycountry-convert==0.7.2
      - pynacl==1.5.0
      - pyogrio==0.9.0
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pytest==8.2.2
      - pytest-cov==5.0.0
      - pytest-mock==3.14.0
      - python-dotenv==1.0.1
      - python-multipart==0.0.17
      - pytils==0.4.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - questionary==2.0.1
      - rapidfuzz==3.9.3
      - referencing==0.35.1
      - repoze-lru==0.7
      - requests==2.31.0
      - rpds-py==0.18.1
      - rpy2==3.5.17
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - selenium==4.20.0
      - setuptools==75.6.0
      - shapely==2.0.4
      - shiny==1.2.1
      - shinywidgets==0.3.4
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sshtunnel==0.4.0
      - starlette==0.41.3
      - statsmodels==0.14.4
      - tenacity==8.3.0
      - thefuzz==0.22.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tools==0.1.9
      - toolz==0.12.1
      - trio==0.25.0
      - trio-websocket==0.11.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - tzlocal==5.2
      - uc-micro-py==1.0.3
      - urllib3==2.2.1
      - uvicorn==0.32.1
      - vega-datasets==0.9.0
      - vl-convert-python==1.7.0
      - watchfiles==0.24.0
      - webencodings==0.5.1
      - websockets==14.1
      - widgetsnbextension==4.0.10
      - wordcloud==1.9.3
      - wsproto==1.2.0
      - xlsxwriter==3.2.0
      - xyzservices==2024.4.0